#[cfg(feature = "day1")]
pub mod day1;
#[cfg(feature = "day2")]
pub mod day2;
#[cfg(feature = "day3")]
pub mod day3;
#[cfg(feature = "day4")]
pub mod day4;
#[cfg(feature = "day5")]
pub mod day5;
#[cfg(feature = "day6")]
pub mod day6;
#[cfg(feature = "day7")]
pub mod day7;
#[cfg(feature = "day8")]
pub mod day8;
#[cfg(feature = "day9")]
pub mod day9;
#[cfg(feature = "day10")]
pub mod day10;
