#[cfg(feature = "day1")]
pub mod day1;
#[cfg(feature = "day2")]
pub mod day2;
#[cfg(feature = "day3")]
pub mod day3;
#[cfg(feature = "day4")]
pub mod day4;
#[cfg(feature = "day5")]
pub mod day5;
#[cfg(feature = "day6")]
pub mod day6;
#[cfg(feature = "day7")]
pub mod day7;
#[cfg(feature = "day8")]
pub mod day8;
#[cfg(feature = "day9")]
pub mod day9;
#[cfg(feature = "day10")]
pub mod day10;
#[cfg(feature = "day11")]
pub mod day11;
#[cfg(feature = "day12")]
pub mod day12;
#[cfg(feature = "day13")]
pub mod day13;
#[cfg(feature = "day14")]
pub mod day14;
#[cfg(feature = "day15")]
pub mod day15;
#[cfg(feature = "day16")]
pub mod day16;
